version: "3.8"

networks:
  services:
    name: services
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
volumes:
  adguard_data: {}

services:

  adguard:
    container_name: adguard
    hostname: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 8080:82/tcp
      - 8443:443/tcp
      - 853:853/tcp
      - 3300:3000/tcp
      - 5353:5353/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_data:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.entrypoints=insecure"
      - "traefik.http.routers.adguardhome.rule=Host(`adguard.$DOMAIN`)"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"
      # - "traefik.http.routers.adguardhome.tls.certresolver=le"
    networks:
      - services
  
  
